DROP SEQUENCE MOVIE_SEQ;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
 
CREATE TABLE MOVIE
(
    MOVIE_ID        NUMBER(3),
    MOVIE_NAME        VARCHAR2(20),
    ACTOR            VARCHAR2(20),
    GENRE            VARCHAR2(10),
    BUDGET            NUMBER(10, 2),
    CONSTRAINT MOVIE_CONS PRIMARY KEY(MOVIE_ID)
);
 
CREATE SEQUENCE MOVIE_SEQ START WITH 100 INCREMENT BY 1;
 
DESC MOVIE;